#!/usr/bin/env python3
"""Generate a minimal run_demo.sh for a newly-onboarded policy repo.

Pairs with deploy_policy + probe_run + infer_io_spec. After those skills
determine the repo's env, entry_script, and checkpoint, this one writes a
tiny standalone shell script the user (or agent) can re-run without any
skill framework loaded.

Inputs:
  --repo-path        : absolute path to the policy repo
  --entry-script     : path (relative to repo) to the main inference/server script
  --checkpoint       : absolute path or HF repo id
  --checkpoint-flag  : CLI flag name, e.g. --checkpoint (default) / --ckpt / --model_path
  --port             : WebSocket port (default 18800)
  --extra-args       : passthrough string
  --out              : where to write the demo script (default: {repo}/run_demo.sh)

Output: an executable shell script that activates the venv, cd's into the
repo, and runs the entry with all flags assembled.
"""
from __future__ import annotations

import argparse
import stat
import sys
from pathlib import Path


TEMPLATE = """#!/usr/bin/env bash
# Auto-generated by generate_run_demo.
# Standalone launcher — does NOT depend on the agent skill framework.
set -euo pipefail

REPO="{repo}"
VENV_PY="$REPO/.venv/bin/python3"
CKPT="{checkpoint}"
PORT="{port}"

if [ ! -x "$VENV_PY" ]; then
  echo "ERROR: venv python not found at $VENV_PY"
  echo "       Run the setup_env skill first."
  exit 1
fi

cd "$REPO"
echo "=== run_demo: $(basename "$REPO") ==="
echo "    entry:      {entry_script}"
echo "    checkpoint: $CKPT"
echo "    port:       $PORT"
echo ""

exec "$VENV_PY" -u "{entry_script}" \\
  {checkpoint_flag} "$CKPT" \\
  --port "$PORT" {extra_args}
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo-path", required=True, type=Path)
    ap.add_argument("--entry-script", required=True)
    ap.add_argument("--checkpoint", required=True)
    ap.add_argument("--checkpoint-flag", default="--checkpoint")
    ap.add_argument("--port", type=int, default=18800)
    ap.add_argument("--extra-args", default="")
    ap.add_argument("--out", default="", help="Default: {repo}/run_demo.sh")
    args = ap.parse_args()

    repo = args.repo_path.resolve()
    if not repo.is_dir():
        print(f"ERROR: repo not found: {repo}")
        return 1

    out_path = Path(args.out) if args.out else repo / "run_demo.sh"
    content = TEMPLATE.format(
        repo=str(repo),
        entry_script=args.entry_script,
        checkpoint=args.checkpoint,
        checkpoint_flag=args.checkpoint_flag,
        port=args.port,
        extra_args=args.extra_args,
    )
    out_path.write_text(content)
    out_path.chmod(out_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print(f"[generate_run_demo] wrote {out_path}")
    print(f"[generate_run_demo] run it with:  {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
