#!/usr/bin/env python3
"""
Auto-generated policy server adapter for {REPO_NAME}.
Wraps the model as a WebSocket policy server via policy_websocket.

Generated by: Robot Ops Agent (wrap_policy skill)
Usage:
    python policy_server.py --port 18800
"""

import argparse
import sys
from pathlib import Path
from typing import Dict

import numpy as np

# Add paths
_root = Path(__file__).resolve().parent
sys.path.insert(0, str(_root))
sys.path.insert(0, str(Path(__file__).resolve().parent / ".." / "agentic" / "policy_websocket" / "src"))  # auto-resolved

from policy_websocket import BasePolicy, WebsocketPolicyServer


class WrappedPolicy(BasePolicy):
    """Adapter wrapping {REPO_NAME} model as a BasePolicy."""

    def __init__(self, **kwargs):
        # TODO: Load model here
        # Example:
        #   from {MODULE} import {MODEL_CLASS}
        #   self.model = {MODEL_CLASS}.from_pretrained(kwargs.get("checkpoint", "..."))
        self.model = None
        self.initialized = False
        print(f"[WrappedPolicy] Model loaded: {REPO_NAME}")

    def infer(self, obs: Dict) -> Dict:
        """Run inference on observation dict, return action dict."""
        # Handle init call (no images)
        if not self._has_images(obs):
            action_dim = obs.get("action_dim", 7)
            self.initialized = True
            return {"actions": np.zeros(action_dim)}

        # TODO: Remap obs to model's expected format
        # model_input = self._remap_obs(obs)

        # TODO: Run model inference
        # raw_action = self.model.predict(model_input)

        # Placeholder: random action
        action = np.random.randn(7) * 0.01
        return {"actions": action}

    def reset(self) -> None:
        self.initialized = False

    @staticmethod
    def _has_images(obs: Dict) -> bool:
        """Check if obs contains image data (distinguishes init from inference)."""
        image_keys = ("agentview_image", "robot0_eye_in_hand_image",
                      "robot0_agentview_left_image", "primary_image",
                      "observation/exterior_image_1_left")
        return any(k in obs and obs[k] is not None for k in image_keys)

    def _remap_obs(self, obs: Dict) -> Dict:
        """Remap raw observation to model's expected format."""
        # TODO: Implement observation remapping specific to this model
        return obs


def main():
    parser = argparse.ArgumentParser(description="{REPO_NAME} Policy Server")
    parser.add_argument("--port", type=int, default=18800)
    parser.add_argument("--checkpoint", type=str, default="")
    args = parser.parse_args()

    policy = WrappedPolicy(checkpoint=args.checkpoint)
    server = WebsocketPolicyServer(policy=policy, host="0.0.0.0", port=args.port)

    print(f"{REPO_NAME} policy server on ws://0.0.0.0:{args.port}")
    server.serve_forever()


if __name__ == "__main__":
    main()
